### ISSUE TITLE
Direct uploads

### ISSUE THREAD

**Issue by antoniobg** [yfxie/activestorage-imgur#2]
Hi! First of all, thank you for the library. It works pretty well uploading images in the conventional way. However, when I try to use the [direct upload](https://guides.rubyonrails.org/active_storage_overview.html#direct-uploads) feature I get a `422 Unprocessable Entity` error. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2571283/55821380-aa2fdd00-5afd-11e9-995c-cbe4ac58ca2b.png">

Are direct uploads support by this gem? Maybe I'm missing something in the configuration. 
This is my `storage.yml` file
```yml

imgur:
  service: Imgur
  client_id: ENV['IMGUR_CLIENT_ID']
  client_secret: ENV['IMGUR_CLIENT_SECRET']
  access_token: ENV['IMGUR_ACCESS_TOKEN']
  refresh_token: ENV['IMGUR_REFRESH_TOKEN']
```
This is my `development.rb` file
```
  config.active_storage.service = :imgur
``` 
This is the form

```haml
= form_for @user, url: user_path(@user) do |f|
  = f.label :bg_picture
  = f.file_field :bg_picture, direct_upload: true
```

And I have this in my `application.js` (using webpacker) 
```
import * as ActiveStorage from "activestorage"

ActiveStorage.start()
``` 

If direct uploads are not supported, do you have any hints on what's needed to be done in order to make it work. I'm happy to help but I'm not really sure about where to start

Thanks again. 

PS: I've tried the direct upload using S3 as a provider and it does work.
